table(function,vars,_,-,[c,d,r]).
table(function,init,_,-,[default,neutral,default]).
table(function,final,_,-,g(r,c)).
table(function,out,_,-,[c,d,r]).
table(function,out(r),_,-,[c,neutral,r]).
table(function,out(a),_,-,[default,neutral,g(r,c)]).
table(function,maybe(b),_,-,[c,f(d,delta),r]).
table(function,maybe(a),_-0,-,[c,f(d,deltaprime),r]).
table(function,maybe(a),_-1,-,[c,f(d,delta),r]).
table(function,found,_-0,-,[f(f(d,delta),deltaprime),neutral,r]).
table(function,found,_-1,-,[f(d,delta),neutral,r]).
table(function,in,_-0,-,[f(c,f(d,deltaprime)),neutral,r]).
table(function,in,_-1,-,[f(c,f(d,delta)),neutral,r]).
table(function,found_end,_-0,-,[c,neutral,g(r,f(f(d,delta),deltaprime))]).
table(function,found_end,_-1,-,[c,neutral,g(r,f(d,delta))]).

table(range_function,vars,_,-,[c,h,r]).
table(range_function,init,_,-,[default,first,default]).
table(range_function,final,_,-,g(r,c)).
table(range_function,out,_,-,[c,deltaprime,r]).
table(range_function,out(r),_,-,[c,deltaprime,r]).
table(range_function,out(a),_,-,[default,deltaprime,g(r,c)]).
table(range_function,maybe(b),_,-,[c,h,r]).
table(range_function,maybe(a),_,-,[c,h,r]).
table(range_function,found_end,_,-,[c,deltaprime,g(r,abs(h-deltaprime))]).
table(range_function,found,_,-,[abs(h-deltaprime),h,r]).
table(range_function,in,_,-,[abs(h-deltaprime),h,r]).